"""Project file walker: prunes ignored dirs, skips binary/oversized files.

Yields a stable, sorted stream of :class:`FileRecord` so chunk output is
deterministic across runs (important for golden-snapshot tests).
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

from engram_mcp import config
from engram_mcp.indexing.ignore import IgnoreMatcher
from engram_mcp.indexing.languages import detect_language


@dataclass(slots=True)
class FileRecord:
    abs_path: Path
    rel_path: str  # POSIX-style, relative to root
    size: int
    language: str | None
    mtime_ns: int = 0


def _looks_binary(path: Path) -> bool:
    """Heuristic: a NUL byte in the first 4 KiB means it's not source text."""
    try:
        with open(path, "rb") as fh:
            return b"\x00" in fh.read(4096)
    except OSError:
        return True


_GENERATED_MARKERS = (
    "@generated",
    "do not edit",
    "auto-generated",
    "autogenerated",
    "code generated by",
    "this file is generated",
    "this file was automatically generated",
)


def looks_generated(text: str) -> bool:
    """Heuristic skip for generated/minified files (a header marker in the
    leading lines, or a very long line). Restricting markers to the head avoids
    false positives from the phrase appearing deeper in legitimate source."""
    head = "\n".join(text.split("\n", 8)[:8]).lower()
    if any(m in head for m in _GENERATED_MARKERS):
        return True
    for line in text.split("\n", 500)[:500]:
        if len(line) > 5000:  # minified / bundled blob
            return True
    return False


def walk(
    root: str | Path,
    ignore: IgnoreMatcher | None = None,
    max_file_bytes: int = config.MAX_FILE_BYTES,
):
    """Yield indexable :class:`FileRecord`s under ``root`` in sorted order."""
    root = Path(root).resolve()
    ignore = ignore or IgnoreMatcher(root)
    for dirpath, dirnames, filenames in os.walk(root):
        # Prune excluded + ignored dirs in place so os.walk never descends in.
        dirnames[:] = sorted(
            d for d in dirnames
            if not ignore.is_excluded_dir(d) and not ignore.is_ignored(Path(dirpath) / d)
        )
        for fn in sorted(filenames):
            abs_path = Path(dirpath) / fn
            # Skip symlinked files (os.walk already doesn't follow dir symlinks);
            # avoids indexing targets outside the project root.
            if os.path.islink(abs_path):
                continue
            rel_path = abs_path.relative_to(root).as_posix()
            if ignore.is_ignored(abs_path):
                continue
            ext = abs_path.suffix.lower()
            if ext in config.BINARY_EXTS:
                continue
            try:
                st = abs_path.stat()
            except OSError:
                continue
            size = st.st_size
            if size == 0 or size > max_file_bytes:
                continue
            lang = detect_language(ext)
            # Unknown extension: only index if it sniffs as text.
            if lang is None and _looks_binary(abs_path):
                continue
            yield FileRecord(abs_path, rel_path, size, lang, st.st_mtime_ns)
