"""Tests for the walker: dir pruning, binary skip, gitignore, language tag."""

from __future__ import annotations

from engram_mcp.indexing.walker import looks_generated, walk


def test_looks_generated_detects_markers_and_minified():
    assert looks_generated("// @generated by protoc\nint x;\n")
    assert looks_generated("/* DO NOT EDIT - autogenerated */\nfoo\n")
    assert not looks_generated(".. DO NOT EDIT THIS FILE!!!\n\nNode\n====\n", "rst")
    assert looks_generated("a" * 6000)  # minified single line
    assert not looks_generated("def foo():\n    return 1\n")


def test_looks_generated_only_matches_head_markers():
    # The phrase appearing deep in a real file must NOT trip the heuristic.
    deep = "\n".join("x = 1" for _ in range(40)) + "\n# do not edit below this line\n"
    assert not looks_generated(deep)
    assert looks_generated("// Code generated by protoc. DO NOT EDIT.\nx = 1\n")


def test_prunes_excluded_dirs_and_binaries(tmp_path):
    (tmp_path / "a.py").write_text("x = 1\n", encoding="utf-8")
    nm = tmp_path / "node_modules"
    nm.mkdir()
    (nm / "b.js").write_text("y = 1\n", encoding="utf-8")
    (tmp_path / "img.png").write_bytes(b"\x89PNG\r\n\x00\x00")

    rels = {r.rel_path for r in walk(tmp_path)}
    assert "a.py" in rels
    assert "node_modules/b.js" not in rels  # pruned dir
    assert "img.png" not in rels  # binary extension


def test_respects_root_gitignore(tmp_path):
    (tmp_path / ".gitignore").write_text("secret.py\n", encoding="utf-8")
    (tmp_path / "secret.py").write_text("x = 1\n", encoding="utf-8")
    (tmp_path / "ok.py").write_text("x = 1\n", encoding="utf-8")

    rels = {r.rel_path for r in walk(tmp_path)}
    assert "ok.py" in rels
    assert "secret.py" not in rels


def test_respects_nested_gitignore(tmp_path):
    sub = tmp_path / "sub"
    sub.mkdir()
    (sub / ".gitignore").write_text("local.py\n", encoding="utf-8")
    (sub / "local.py").write_text("x = 1\n", encoding="utf-8")
    (sub / "keep.py").write_text("x = 1\n", encoding="utf-8")
    (tmp_path / "top.py").write_text("x = 1\n", encoding="utf-8")

    rels = {r.rel_path for r in walk(tmp_path)}
    assert "top.py" in rels
    assert "sub/keep.py" in rels
    assert "sub/local.py" not in rels  # nested .gitignore


def test_gitignore_negation_within_a_file(tmp_path):
    (tmp_path / ".gitignore").write_text("*.log\n!keep.log\n", encoding="utf-8")
    (tmp_path / "a.log").write_text("x\n", encoding="utf-8")
    (tmp_path / "keep.log").write_text("x\n", encoding="utf-8")

    rels = {r.rel_path for r in walk(tmp_path)}
    assert "a.log" not in rels
    assert "keep.log" in rels


def test_language_detection_and_size_cap(tmp_path):
    (tmp_path / "a.py").write_text("x = 1\n", encoding="utf-8")
    (tmp_path / "large.rst").write_text("a" * 1_500_000, encoding="utf-8")
    (tmp_path / "big.py").write_text("# " + "a" * 2_000_000 + "\n", encoding="utf-8")

    recs = {r.rel_path: r for r in walk(tmp_path)}
    assert recs["a.py"].language == "python"
    assert recs["large.rst"].language == "rst"
    assert "big.py" not in recs  # exceeds MAX_FILE_BYTES


def test_skips_empty_files(tmp_path):
    (tmp_path / "empty.py").write_text("", encoding="utf-8")
    (tmp_path / "a.py").write_text("x = 1\n", encoding="utf-8")
    rels = {r.rel_path for r in walk(tmp_path)}
    assert "a.py" in rels
    assert "empty.py" not in rels
